version: "3.8"

services:

  minio:
    image: minio/minio:latest
    hostname: minio
    container_name: minio
    volumes:
      - ./local/s3/data:/data
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
      MINIO_BUCKET: somebucketname
    command: server --console-address ":9001" /data
    expose:
      - "9000"  #api
      - "9001"  #console
    healthcheck:
        #healthcheck has been modified with the last image (2023-11-06) curl has been removed (see log in inspect)
#      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
#      interval: 30s
#      timeout: 20s
#      retries: 3
      test: timeout 5s bash -c ':> /dev/tcp/127.0.0.1/9000' || exit 1
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 5s      
      
  nginx: #for minio
    image: nginx:alpine
    hostname: nginx
    container_name: s3_nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9000:9000"
      - "9001:9001"
    depends_on:
      - minio

  minioclient:
    image: minio/mc
    hostname: minioclient
    container_name: minioclient
    volumes:
      - ./local/import:/import
    depends_on:
      minio: 
        condition: service_healthy
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc config host rm local;
      /usr/bin/mc config host add --quiet --api s3v4 local http://minio:9000 minio minio123; 
      /usr/bin/mc rb --force local/somebucketname/;
      /usr/bin/mc mb local/somebucketname/ --region=eu-west-3; 
      /usr/bin/mc anonymous set public local/somebucketname;
      /usr/bin/mc cp /import/* local/somebucketname --recursive;
      exec sleep inf;
      "
      #rb is to remove bucket
      #mb is to create bucket
      #anonymous has replaced policy
      #to add some file in the bucket, 
      #  first mount volume 
      #  then mc cp <mount_point> local/somebucketname/ 
      #exec sleep inf is set to no have the container shut down
      #otherwise use exit 0;


  awscli:
    image: public.ecr.aws/aws-cli/aws-cli:latest
    #image: amazon/aws-cli:latest
    hostname: awscli
    container_name: awscli
    volumes:
      - ./local/awscli:/root/.aws
    depends_on:
      minio:
        condition: service_healthy
    entrypoint: > 
      /bin/sh -c "
      exec sleep inf;
      "
      #how to list files in the bucket: 
      # > docker exec -ti awscli /bin/sh
      # sh# aws --endpoint-url=http://minio:9000 s3 ls s3://somebucketname
      # sh# aws --endpoint-url=http://minio:9000 s3 ls s3://somebucketname --recursive 


networks:
  default:
    name: myproject_network
