version: '3'

services:
  minio:
    image: minio/minio:latest
    hostname: minio
    container_name: s3_minio
    volumes:
      - ./storage/:/storage
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    command: server --console-address ":9001" /storage
    expose:
      - "9000"  #api
      - "9001"  #console
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3

  createbuckets:
    image: minio/mc:latest
    container_name: s3_createbuckets
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c '
      until (/usr/bin/mc config host add myminio http://s3_minio:9000 minio minio123 ) do echo '...waiting...' && sleep 1; done;
      [[ ! -z "`/usr/bin/mc ls myminio | grep test`" ]] || /usr/bin/mc mb myminio/test;
      /usr/bin/mc policy set download myminio/test;
      exit 0;
      '

  nginx:
    image: nginx:alpine
    hostname: nginx
    container_name: s3_nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9000:9000"
      - "9001:9001"
    depends_on:
      - minio
